import { parseVoiceGuidelines } from '../shared/voice';
import type { IcpDraft, SourceDoc, Unverified, VerifiedKnowledge, VoiceDraft } from './synthesize';

// Markdown for the generated profile: voice.md (read by the engine's draft checker) and
// knowledge.md (the research brief a person reviews).

// One "## Heading" section of a markdown file, heading included, up to the next "## ".
export function section(markdown: string, heading: string): string {
  const start = markdown.search(new RegExp(`^## ${heading.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*$`, 'm'));
  if (start < 0) return '';
  const rest = markdown.slice(start);
  const next = rest.slice(3).search(/^## /m);
  return (next < 0 ? rest : rest.slice(0, next + 3)).trim();
}

const bullets = (items: string[], empty: string) => (items.length ? items.map(i => `- ${i}`).join('\n') : `- ${empty}`);

export interface VoiceInput {
  company: string;
  domain: string;
  date: string;
  voice: VoiceDraft;
  proofPoints: VerifiedKnowledge['proofPoints'];
  urlFor: (id: string) => string;
  // The template voice.md: its hard constraints, structure and checklist are kept as is.
  template: string;
}

export function renderVoice({ company, domain, date, voice, proofPoints, urlFor, template }: VoiceInput): string {
  const templateBanned = section(template, 'Banned buzzwords').replace(/^## Banned buzzwords\s*/, '').split(',');
  const banned = [...new Set([...templateBanned, ...voice.wordsToAvoid].map(w => w.replace(/[,\n]/g, ' ').trim().toLowerCase()).filter(w => w && w.length <= 40))];

  const markdown = [
    `# Voice and copy guidelines: ${company}`,
    `Generated by \`npm run research\` for ${domain} on ${date}. Review before use; the sources are listed in knowledge.md.`,
    `## Tone\n\n${bullets(voice.tone, 'Plain, direct, peer-to-peer.')}`,
    `## Offer\n\n- **What we offer:** ${voice.offer}\n- **Ask:** ${voice.callToAction}\n- **Sign-off:** ${voice.senderName}`,
    `## Proof points\n\nOnly these may be used as social proof. Each quote was found word for word on its source page; confirm the client approves using it.\n\n${bullets(
      proofPoints.map(p => `${p.claim}: "${p.quote}" (${urlFor(p.source)})`),
      "None found. Don't use social-proof lines until one is added and approved.",
    )}`,
    `## Their language\n\n- Words they use: ${voice.wordsTheyUse.join(', ') || '-'}\n- Phrases from their copy: ${voice.samplePhrases.map(p => `"${p.quote}"`).join('; ') || '-'}`,
    section(template, 'Hard constraints for email copy'),
    `## Banned buzzwords\n\n${banned.join(', ')}`,
    section(template, 'Structure (first touch)'),
    section(template, 'Review checklist'),
  ]
    .filter(Boolean)
    .join('\n\n');

  // The draft checker reads its limits from these lines; fail here, not at engine start.
  parseVoiceGuidelines(markdown);
  return `${markdown}\n`;
}

export interface KnowledgeInput {
  company: string;
  domain: string;
  date: string;
  model: string;
  knowledge: VerifiedKnowledge;
  icpDraft: IcpDraft;
  buildNotes: string[];
  docs: SourceDoc[];
  unverified: Unverified[];
  skipped: { url: string; reason: string }[];
}

export function renderKnowledge(input: KnowledgeInput): string {
  const { knowledge: k, docs } = input;
  const cite = (id: string) => ` [${id}]`;
  const count = (kind: string) => docs.filter(d => (kind === 'site' ? d.kind !== 'search' && d.kind !== 'notes' : d.kind === kind)).length;

  const sections: [string, string[], string?][] = [
    ['What they sell', k.products.map(p => `**${p.name}**: ${p.description}${cite(p.source)}`)],
    ['Value propositions', k.valueProps.map(c => `${c.claim}${cite(c.source)}`)],
    ['Pricing', k.pricing.map(c => `${c.claim}${cite(c.source)}`)],
    ['Customers (verified)', k.customers.map(c => `**${c.name}**: "${c.quote}"${cite(c.source)}`), 'None verified.'],
    ['Proof points (verified)', k.proofPoints.map(p => `${p.claim}: "${p.quote}"${cite(p.source)}`), 'None verified.'],
    ['Competitors', k.competitors.map(c => `${c.name}${cite(c.source)}`)],
    ['Differentiators', k.differentiators.map(c => `${c.claim}${cite(c.source)}`)],
    ['Markets', k.markets.map(c => `${c.claim}${cite(c.source)}`)],
    ['Likely objections (inferred)', k.likelyObjections],
    ['Signals that a company needs this now (inferred)', k.signalsToWatch],
    ['Why this ICP', input.icpDraft.rationale.map(c => `${c.claim}${cite(c.source)}`)],
  ];

  const review = [
    '**Industry names** in icp.json match the labels your data provider returns (Lusha, Apollo...). The scorer matches them exactly, so "SaaS" will not match "Software Development".',
    '**Dealbreakers** and excluded keywords do not rule out real customers.',
    '**Countries** are the markets they sell to, not only where they are based.',
    '**Proof points** in voice.md are real and the client approves using them.',
    '**Personas** are the people who actually buy.',
    ...input.buildNotes,
  ];

  return [
    `# ${input.company}: research brief`,
    k.oneLiner,
    `Generated by \`npm run research\` for ${input.domain} on ${input.date} with ${input.model}, from ${docs.length} sources (${count('site')} website pages, ${count('search')} search results, ${count('notes')} notes). Facts cite source ids (see Sources). Items marked *inferred* are the model's judgement, not stated facts.`,
    `## Review before using this profile\n\n${review.map(r => `- [ ] ${r}`).join('\n')}`,
    ...sections.map(([title, items, empty]) => `## ${title}\n\n${bullets(items, empty ?? 'Nothing found in the sources.')}`),
    `## Could not be verified (dropped)\n\n${bullets(
      input.unverified.map(u => `${u.item}: ${u.reason}`),
      'Nothing was dropped.',
    )}`,
    `## Sources\n\n${docs.map(d => `- **${d.id}** (${d.kind}) ${d.title ? `${d.title}: ` : ''}${d.url}`).join('\n')}`,
    input.skipped.length ? `## Pages not read\n\n${input.skipped.slice(0, 30).map(s => `- ${s.url}: ${s.reason}`).join('\n')}` : '',
  ]
    .filter(Boolean)
    .join('\n\n')
    .concat('\n');
}
